version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    depends_on:
      - broker
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083

  fruits-api:
    container_name: fruits-api
    depends_on:
      - broker
      - zookeeper
    build:
      context: ./backend/FruitsApi
    environment:
      KafkaBootstrapServers: broker:9092
      KafkaTopic: newFruit
    ports:
      - "5177:8000"

  fruit-recognition-service:
    container_name: fruit-recognition-service
    depends_on:
      - broker
      - zookeeper
    build:
      context: ./backend/FruitRecognitionService
    environment:
      KafkaBootstrapServers: broker:9092
      KafkaTopic: newFruit
      ClassifierBaseUrl: http://fruit-classifier:6003
    ports:
      - "5227:8000"

  fruit-classifier:
    container_name: fruit-classifier
    depends_on:
      - broker
      - zookeeper
    build:
      context: ./backend/FruitClassifier
    ports:
      - "6003:6003"

  fruit-frontend:
    container_name: fruit-frontend
    depends_on:
      - broker
      - zookeeper
    build:
      context: ./frontend
    ports:
      - "4200:80"