name: FruitClassifier

channels:
  - defaults
  - conda-forge

dependencies:
  - pip=20.1.1
  - python=3.7
  - poppler==21.08.0
  - pip:
    - tensorflow==1.15
    - keras
    - Pillow==9.1.1
    - fastapi
    - uvicorn
    - h5py==2.10.0
    - python-multipart==0.0.5
